export const NAV_LINKS = [
  { label: "Home", href: "/", hasMegaMenu: false },
  { label: "Services", href: "/services", hasMegaMenu: false },
  { label: "Products", href: "/catalog", hasMegaMenu: true },
  { label: "Portfolio", href: "/portfolio", hasMegaMenu: false },
  { label: "Investors", href: "/investors", hasMegaMenu: false },
  { label: "Contact", href: "/contact", hasMegaMenu: false },
] as const;

export const SERVICES = [
  {
    title: "Large Format Printing",
    description: "Architectural wraps and industrial-scale visual systems engineered with sub-millimeter precision. From building facades to exhibition halls.",
    features: ["Up to 5m wide seamless prints", "UV-resistant inks", "Sub-millimeter accuracy", "Indoor & outdoor rated"],
    icon: "Ruler" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/service-large-format.webp",
  },
  {
    title: "Event Printing",
    description: "Setting the stage for high-impact launches and corporate prestige with vibrant, calibrated color accuracy across every touchpoint.",
    features: ["Same-day rush available", "Stage backdrops & banners", "Pop-up displays", "Complete event kits"],
    icon: "PartyPopper" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/service-event-printing.webp",
  },
  {
    title: "Banner Printing",
    description: "Resilient vinyl and premium fabric solutions for architectural and outdoor branding that withstand the elements.",
    features: ["Wind-resistant mesh", "Double-sided printing", "Hemmed & grommeted", "Custom sizes"],
    icon: "Flag" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/service-banner-printing.webp",
  },
  {
    title: "Panel Printing",
    description: "Rigid substrate printing on Dibond, acrylic, and composite materials for gallery-grade permanent installations.",
    features: ["Aluminum composite", "Acrylic & PVC", "Direct-to-substrate", "10+ year durability"],
    icon: "LayoutGrid" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/service-panel-printing.webp",
  },
  {
    title: "Poster & Large Display",
    description: "High-resolution poster printing for retail, exhibitions, and promotional campaigns that demand attention.",
    features: ["Photo-quality output", "Matte & gloss finishes", "Mounting options", "Bulk pricing"],
    icon: "Image" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/product-poster-set.webp",
  },
  {
    title: "Marketing Materials",
    description: "Premium catalogs, flyers, and brand collateral that translate digital identities into high-fidelity tactile reality.",
    features: ["Spot UV & foil options", "Custom die-cutting", "Premium paper stocks", "Brand consistency"],
    icon: "Megaphone" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/product-marketing-kit.webp",
  },
  {
    title: "Custom Production",
    description: "Bespoke printing solutions for non-standard surfaces, specialized industrial environments, and high-spec architectural projects.",
    features: ["Material R&D", "Prototype runs", "Technical consultation", "Any substrate"],
    icon: "Settings" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
] as const;

export const PORTFOLIO_PROJECTS = [
  {
    title: "Global Tech Summit 2024",
    category: "Event Branding",
    description: "Comprehensive event branding and immersive environment design with precision color matching across 12,000 sqm of exhibition space.",
    featured: true,
    image: "/images/pelmeltech/portfolio-corporate-event.webp",
  },
  {
    title: "Flagship Retail Store",
    category: "Retail Display",
    description: "Full storefront vinyl and interior graphics for a luxury fashion brand's flagship location.",
    featured: false,
    image: "/images/pelmeltech/portfolio-retail-display.webp",
  },
  {
    title: "Corporate HQ Redesign",
    category: "Architectural Signage",
    description: "Complete wayfinding and brand integration for a Fortune 500 corporate campus.",
    featured: false,
    image: "/images/pelmeltech/portfolio-exhibition-panels.webp",
  },
  {
    title: "Music Festival Stage Design",
    category: "Event Printing",
    description: "Large-scale stage backdrops and environmental graphics for a 50,000-attendee music festival.",
    featured: false,
    image: "/images/pelmeltech/portfolio-stage-backdrop.webp",
  },
  {
    title: "Automotive Showroom",
    category: "Premium Display",
    description: "High-resolution wall murals and lightbox displays for a premium automotive dealership network.",
    featured: false,
    image: "/images/pelmeltech/portfolio-poster-campaign.webp",
  },
  {
    title: "Urban Billboard Campaign",
    category: "Outdoor Advertising",
    description: "City-wide billboard campaign with weather-resistant large format prints across 40 locations.",
    featured: false,
    image: "/images/pelmeltech/portfolio-outdoor-campaign.webp",
  },
] as const;

export const STATS = [
  { value: 250, suffix: "+", label: "Global Partners" },
  { value: 99.8, suffix: "%", label: "Color Accuracy" },
  { value: 0.01, suffix: "mm", label: "Print Tolerance" },
  { value: 24, suffix: "/7", label: "Production Capacity" },
] as const;

export const TESTIMONIALS = [
  {
    quote: "PelmelTech's attention to color accuracy and structural integrity is unparalleled. They handled our multi-city rollout without a single defect.",
    author: "Jane Doe",
    role: "CMO, Zenith Global",
    initials: "JD",
  },
  {
    quote: "The precision in their large-format prints transformed our exhibition presence. A truly professional partner from design to final install.",
    author: "Mark Sloan",
    role: "Director of Logistics, Aerotech",
    initials: "MS",
  },
  {
    quote: "Exceptional service. Their ability to handle high-volume, premium requests with tight deadlines has made them our go-to printing agency.",
    author: "Robert Lee",
    role: "Founder, Luminous Design",
    initials: "RL",
  },
  {
    quote: "We switched to PelmelTech for our annual reports and the quality difference was immediately noticeable. Crisp typography, vibrant covers.",
    author: "Sarah Chen",
    role: "VP of Marketing, Nexus Corp",
    initials: "SC",
  },
  {
    quote: "Their team delivered 500 retail displays across three countries in under two weeks. Flawless coordination and zero reprints needed.",
    author: "Ahmed Khalil",
    role: "Operations Lead, Orion Retail",
    initials: "AK",
  },
  {
    quote: "The packaging prototypes PelmelTech produced helped us close our Series B. Investors could feel the product quality before it even launched.",
    author: "Lisa Wang",
    role: "CEO, Bloom Cosmetics",
    initials: "LW",
  },
  {
    quote: "We needed UV-resistant signage for our desert resort and PelmelTech nailed it. Two years in harsh sun and the colors still pop.",
    author: "Omar Nasser",
    role: "Facilities Director, Oasis Hotels",
    initials: "ON",
  },
  {
    quote: "From concept sketches to final delivery, PelmelTech kept us informed at every step. Rare to find that level of transparency in this industry.",
    author: "Emily Torres",
    role: "Brand Manager, Velocity Sports",
    initials: "ET",
  },
  {
    quote: "Our museum exhibition required archival-grade prints with exact Pantone matching. PelmelTech was the only vendor who got it right first try.",
    author: "Dr. Hans Weber",
    role: "Curator, Modern Art Basel",
    initials: "HW",
  },
  {
    quote: "The vehicle wraps they produced for our fleet are stunning. Consistent quality across 200 trucks, and the install teams were incredibly efficient.",
    author: "Carlos Mendez",
    role: "Fleet Manager, Swift Logistics",
    initials: "CM",
  },
  {
    quote: "PelmelTech transformed our trade show booth from forgettable to show-stopping. We won Best Booth at CES three years running thanks to them.",
    author: "Priya Sharma",
    role: "Events Director, TechNova",
    initials: "PS",
  },
  {
    quote: "Their eco-friendly printing options helped us meet our sustainability goals without compromising on visual impact. A win-win partnership.",
    author: "Daniel Eriksson",
    role: "Sustainability Lead, GreenPath",
    initials: "DE",
  },
  {
    quote: "We print thousands of luxury invitations each quarter. PelmelTech's letterpress and foil work is consistently the finest we've encountered.",
    author: "Victoria Hart",
    role: "Creative Director, Élite Events",
    initials: "VH",
  },
  {
    quote: "Quick turnaround, premium materials, and pricing that actually makes sense. PelmelTech is our secret weapon for client presentations.",
    author: "James Park",
    role: "Partner, Skyline Architecture",
    initials: "JP",
  },
  {
    quote: "The backlit fabric prints for our flagship store windows were breathtaking. Customers literally stop on the street to photograph them.",
    author: "Nina Rossi",
    role: "Visual Merchandiser, Luxe Fashion",
    initials: "NR",
  },
  {
    quote: "We've worked with a dozen print vendors over the years. PelmelTech is the first one where we never had to request a reprint.",
    author: "Thomas Blake",
    role: "Procurement Director, Atlas Media",
    initials: "TB",
  },
  {
    quote: "Their dimensional signage for our new headquarters made an incredible first impression. Every visitor comments on the lobby installation.",
    author: "Rachel Kim",
    role: "Office Manager, Pinnacle Finance",
    initials: "RK",
  },
  {
    quote: "PelmelTech handled our entire conference identity — badges, banners, stage graphics, wayfinding. Seamless brand consistency throughout.",
    author: "David Okafor",
    role: "Conference Producer, Summit Global",
    initials: "DO",
  },
  {
    quote: "The color proofing process they use gave us total confidence before committing to our 10,000-unit product packaging run.",
    author: "Mia Johnson",
    role: "Product Manager, FreshBrew Co",
    initials: "MJ",
  },
  {
    quote: "Our real estate signage needs are demanding — fast turnarounds, varied sizes, weather resistance. PelmelTech delivers every single time.",
    author: "Alex Dubois",
    role: "Marketing Head, Prime Properties",
    initials: "AD",
  },
] as const;
