export const NAV_LINKS = [
  { label: "Home", href: "/", hasMegaMenu: false },
  { label: "Services", href: "/services", hasMegaMenu: false },
  { label: "Products", href: "/catalog", hasMegaMenu: true },
  { label: "Contact", href: "/contact", hasMegaMenu: false },
] as const;

export const SERVICES = [
  {
    title: "Large Format Printing",
    description: "Architectural wraps and industrial-scale visual systems engineered with sub-millimeter precision. From building facades to exhibition halls.",
    features: ["Up to 5m wide seamless prints", "UV-resistant inks", "Sub-millimeter accuracy", "Indoor & outdoor rated"],
    icon: "Ruler" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/service-large-format.webp",
  },
  {
    title: "Event Printing",
    description: "Setting the stage for high-impact launches and corporate prestige with vibrant, calibrated color accuracy across every touchpoint.",
    features: ["Same-day rush available", "Stage backdrops & banners", "Pop-up displays", "Complete event kits"],
    icon: "PartyPopper" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/service-event-printing.webp",
  },
  {
    title: "Banner Printing",
    description: "Resilient vinyl and premium fabric solutions for architectural and outdoor branding that withstand the elements.",
    features: ["Wind-resistant mesh", "Double-sided printing", "Hemmed & grommeted", "Custom sizes"],
    icon: "Flag" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/service-banner-printing.webp",
  },
  {
    title: "Panel Printing",
    description: "Rigid substrate printing on Dibond, acrylic, and composite materials for gallery-grade permanent installations.",
    features: ["Aluminum composite", "Acrylic & PVC", "Direct-to-substrate", "10+ year durability"],
    icon: "LayoutGrid" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/service-panel-printing.webp",
  },
  {
    title: "Poster & Large Display",
    description: "High-resolution poster printing for retail, exhibitions, and promotional campaigns that demand attention.",
    features: ["Photo-quality output", "Matte & gloss finishes", "Mounting options", "Bulk pricing"],
    icon: "Image" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/product-poster-set.webp",
  },
  {
    title: "Marketing Materials",
    description: "Premium catalogs, flyers, and brand collateral that translate digital identities into high-fidelity tactile reality.",
    features: ["Spot UV & foil options", "Custom die-cutting", "Premium paper stocks", "Brand consistency"],
    icon: "Megaphone" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/product-marketing-kit.webp",
  },
  {
    title: "Custom Production",
    description: "Bespoke printing solutions for non-standard surfaces, specialized industrial environments, and high-spec architectural projects.",
    features: ["Material R&D", "Prototype runs", "Technical consultation", "Any substrate"],
    icon: "Settings" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
] as const;
