export const NAV_LINKS = [
  { label: "Home", href: "/", hasMegaMenu: false },
  { label: "Services", href: "/services", hasMegaMenu: false },
  { label: "Products", href: "/catalog", hasMegaMenu: true },
  { label: "Portfolio", href: "/portfolio", hasMegaMenu: false },
  { label: "Investors", href: "/investors", hasMegaMenu: false },
  { label: "Contact", href: "/contact", hasMegaMenu: false },
] as const;

export const PRODUCT_MENU = {
  categories: [
    {
      title: "Printing Machines",
      description: "High-performance printers for every scale and application.",
      icon: "Printer" as const,
      image: "/images/pelmeltech/product-large-format-printer.webp",
      items: [
        { label: "Standard Printers", href: "/catalog?category=standard-printers" },
        { label: "Large-Format Printers", href: "/catalog?category=large-format" },
        { label: "Event Printers", href: "/catalog?category=event-printers" },
        { label: "Industrial Printers", href: "/catalog?category=industrial" },
        { label: "Plotters", href: "/catalog?category=plotters" },
      ],
    },
    {
      title: "Printing Materials",
      description: "Durable substrates for indoor and outdoor visibility.",
      icon: "Layers" as const,
      image: "/images/pelmeltech/product-outdoor-banner.webp",
      items: [
        { label: "Banners", href: "/catalog?category=banners" },
        { label: "Panels", href: "/catalog?category=panels" },
        { label: "Posters", href: "/catalog?category=posters" },
        { label: "Stickers & Vinyl", href: "/catalog?category=vinyl" },
        { label: "Roll-Up Displays", href: "/catalog?category=rollups" },
      ],
    },
    {
      title: "Consumables & Accessories",
      description: "Essential inks, papers, parts, and maintenance supplies.",
      icon: "Package" as const,
      image: "/images/pelmeltech/services-print-materials.webp",
      items: [
        { label: "Ink", href: "/catalog?category=ink" },
        { label: "Toner", href: "/catalog?category=toner" },
        { label: "Paper Rolls", href: "/catalog?category=paper-rolls" },
        { label: "Printer Parts", href: "/catalog?category=parts" },
        { label: "Maintenance Kits", href: "/catalog?category=maintenance" },
      ],
    },
  ],
  featured: {
    title: "Featured Products",
    image: "/images/pelmeltech/catalog-hero.webp",
    items: [
      { label: "Best Sellers", href: "/catalog?filter=bestsellers", accent: true },
      { label: "New Arrivals", href: "/catalog?filter=new", accent: false },
      { label: "Product Catalog", href: "/catalog", accent: false },
    ],
    cta: {
      label: "Request a Quote",
      href: "/contact",
    },
  },
} as const;

export const SERVICES = [
  {
    title: "Large Format Printing",
    description: "Architectural wraps and industrial-scale visual systems engineered with sub-millimeter precision. From building facades to exhibition halls.",
    features: ["Up to 5m wide seamless prints", "UV-resistant inks", "Sub-millimeter accuracy", "Indoor & outdoor rated"],
    icon: "Ruler" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/service-large-format.webp",
  },
  {
    title: "Event Printing",
    description: "Setting the stage for high-impact launches and corporate prestige with vibrant, calibrated color accuracy across every touchpoint.",
    features: ["Same-day rush available", "Stage backdrops & banners", "Pop-up displays", "Complete event kits"],
    icon: "PartyPopper" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/service-event-printing.webp",
  },
  {
    title: "Banner Printing",
    description: "Resilient vinyl and premium fabric solutions for architectural and outdoor branding that withstand the elements.",
    features: ["Wind-resistant mesh", "Double-sided printing", "Hemmed & grommeted", "Custom sizes"],
    icon: "Flag" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/service-banner-printing.webp",
  },
  {
    title: "Panel Printing",
    description: "Rigid substrate printing on Dibond, acrylic, and composite materials for gallery-grade permanent installations.",
    features: ["Aluminum composite", "Acrylic & PVC", "Direct-to-substrate", "10+ year durability"],
    icon: "LayoutGrid" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/service-panel-printing.webp",
  },
  {
    title: "Poster & Large Display",
    description: "High-resolution poster printing for retail, exhibitions, and promotional campaigns that demand attention.",
    features: ["Photo-quality output", "Matte & gloss finishes", "Mounting options", "Bulk pricing"],
    icon: "Image" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/product-poster-set.webp",
  },
  {
    title: "Marketing Materials",
    description: "Premium catalogs, flyers, and brand collateral that translate digital identities into high-fidelity tactile reality.",
    features: ["Spot UV & foil options", "Custom die-cutting", "Premium paper stocks", "Brand consistency"],
    icon: "Megaphone" as const,
    accent: "magenta" as const,
    image: "/images/pelmeltech/product-marketing-kit.webp",
  },
  {
    title: "Custom Production",
    description: "Bespoke printing solutions for non-standard surfaces, specialized industrial environments, and high-spec architectural projects.",
    features: ["Material R&D", "Prototype runs", "Technical consultation", "Any substrate"],
    icon: "Settings" as const,
    accent: "cyan" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
] as const;

export const PRODUCTS = [
  {
    name: "ApexJet Office Pro 420",
    category: "Standard Printers",
    description: "Reliable color printer for offices, agencies, schools, and everyday business documents.",
    price: "Request quote",
    badge: "Office",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/product-large-format-printer.webp",
  },
  {
    name: "ColorLine Business MFP",
    category: "Standard Printers",
    description: "Multifunction printer with scanning, copying, and sharp color output for busy teams.",
    price: "Request quote",
    badge: "Popular",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/catalog-hero.webp",
  },
  {
    name: "WidePro LX 1600",
    category: "Large Format Printers",
    description: "Large-format printer for banners, posters, signage, backdrops, and retail graphics.",
    price: "Request quote",
    badge: "Bestseller",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-large-format-printer.webp",
  },
  {
    name: "WidePro UV Hybrid 2500",
    category: "Large Format Printers",
    description: "Hybrid UV printer for rigid panels, vinyl, acrylic, PVC, and premium display substrates.",
    price: "Request quote",
    badge: "Premium",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/service-large-format.webp",
  },
  {
    name: "BannerMax Roll Printer",
    category: "Large Format Printers",
    description: "Roll-to-roll printer tuned for outdoor banners, mesh, vinyl, and campaign production.",
    price: "Request quote",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/product-outdoor-banner.webp",
  },
  {
    name: "EventSnap Photo Printer",
    category: "Event Printers",
    description: "Compact event printer for activations, photo booths, launches, and on-site brand moments.",
    price: "Request quote",
    badge: "Event",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/service-event-printing.webp",
  },
  {
    name: "ProductionLine X9",
    category: "Industrial Printers",
    description: "Industrial printer for high-volume print rooms, professional shops, and continuous production.",
    price: "Request quote",
    badge: "Industrial",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/catalog-hero.webp",
  },
  {
    name: "Flatbed Pro Rigid 1325",
    category: "Industrial Printers",
    description: "Flatbed printer for direct-to-substrate production on panels, boards, acrylic, and signage.",
    price: "Request quote",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/product-rigid-panel.webp",
  },
  {
    name: "PlanMaster CAD Plotter",
    category: "Plotters",
    description: "Precision plotter for technical drawings, construction plans, maps, and engineering documents.",
    price: "Request quote",
    badge: "Precision",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/product-large-format-printer.webp",
  },
  {
    name: "CutLine Vinyl Plotter",
    category: "Plotters",
    description: "Contour-cut plotter for stickers, decals, vinyl graphics, window lettering, and labels.",
    price: "Request quote",
    badge: "New",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-vinyl-roll.webp",
  },
  {
    name: "Titan Industrial Mesh",
    category: "Banners & Mesh",
    description: "High-durability wind-resistant mesh designed for large-scale outdoor installations.",
    price: "$89.00",
    badge: "Bestseller",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-outdoor-banner.webp",
  },
  {
    name: "AluCore Rigid Panels",
    category: "Rigid Panels",
    description: "Premium composite aluminum boards with UV-protected inks for architectural signage.",
    price: "$125.00",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/product-rigid-panel.webp",
  },
  {
    name: "Acrylic Display Panels",
    category: "Rigid Panels",
    description: "Polished acrylic panels for showroom signage, indoor branding, and premium display systems.",
    price: "$145.00",
    badge: "Premium",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-rigid-panel.webp",
  },
  {
    name: "Lumina Backlit Fabric",
    category: "Soft Signage",
    description: "Sustainably sourced textiles optimized for high-contrast lightboxes.",
    price: "$210.00",
    badge: "Eco-Friendly",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/product-event-backdrop.webp",
  },
  {
    name: "Precision Wall Vinyl",
    category: "Vinyl & Wraps",
    description: "Professional-grade adhesive vinyl with bubble-free technology for office branding.",
    price: "$45.00/sqm",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/product-vinyl-roll.webp",
  },
  {
    name: "FloorGuard Laminated Vinyl",
    category: "Vinyl & Wraps",
    description: "Durable floor graphics with anti-slip laminate for retail routes and event wayfinding.",
    price: "$52.00/sqm",
    badge: "Durable",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/product-vinyl-roll.webp",
  },
  {
    name: "Apex Retractable Stand",
    category: "Exhibition",
    description: "Heavy-duty base and stay-flat premium print media for trade shows.",
    price: "$155.00",
    badge: "Popular",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-rollup-banner.webp",
  },
  {
    name: "ExpoLite Pop-Up Wall",
    category: "Exhibition",
    description: "Portable pop-up display wall for trade shows, activations, showrooms, and corporate booths.",
    price: "$690.00",
    badge: "Event",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-rollup-banner.webp",
  },
  {
    name: "Aluminum Dibond Panels",
    category: "Rigid Panels",
    description: "Rigid architectural panels designed for 10+ year exterior durability.",
    price: "$85.00",
    badge: "Industrial",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/product-rigid-panel.webp",
  },
  {
    name: "CMYK Eco-Solvent Ink Set",
    category: "Ink & Toner",
    description: "Four-color ink set for vibrant outdoor graphics, banners, vinyl, and large-format media.",
    price: "$165.00",
    badge: "CMYK",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
  {
    name: "UV Rigid Ink Cartridge",
    category: "Ink & Toner",
    description: "UV ink cartridge for rigid substrate printing with strong adhesion and crisp detail.",
    price: "$210.00",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
  {
    name: "Office Toner Twin Pack",
    category: "Ink & Toner",
    description: "High-yield toner pack for business printers, reports, proposals, and office documents.",
    price: "$118.00",
    badge: "Value",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
  {
    name: "Premium Photo Paper Roll",
    category: "Paper & Rolls",
    description: "Smooth photo paper roll for posters, campaign visuals, retail displays, and proofing.",
    price: "$74.00",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/product-poster-set.webp",
  },
  {
    name: "Heavyweight Banner Roll",
    category: "Paper & Rolls",
    description: "Durable banner media roll for outdoor campaigns, event branding, and storefront graphics.",
    price: "$132.00",
    badge: "Outdoor",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-outdoor-banner.webp",
  },
  {
    name: "Precision Printhead Module",
    category: "Printer Parts",
    description: "Replacement printhead module for restoring sharp output and consistent ink delivery.",
    price: "$340.00",
    badge: "Parts",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
  {
    name: "Media Feed Roller Kit",
    category: "Printer Parts",
    description: "Roller replacement kit for smoother media feeding and reduced production misalignment.",
    price: "$86.00",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
  {
    name: "Cutting Blade Holder Set",
    category: "Printer Parts",
    description: "Blade holder set for vinyl plotters, contour cutting, decals, and label production.",
    price: "$58.00",
    badge: "Tooling",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/product-vinyl-roll.webp",
  },
  {
    name: "Nozzle Cleaning Station",
    category: "Maintenance Tools",
    description: "Cleaning station for daily printer care, nozzle maintenance, and production reliability.",
    price: "$95.00",
    badge: "Care",
    badgeColor: "cyan" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
  {
    name: "Calibration Alignment Kit",
    category: "Maintenance Tools",
    description: "Alignment tools for print accuracy, color checks, registration tuning, and operator setup.",
    price: "$125.00",
    badge: null,
    badgeColor: null,
    image: "/images/pelmeltech/catalog-hero.webp",
  },
  {
    name: "Printer Maintenance Kit",
    category: "Maintenance Tools",
    description: "Complete kit with wipes, swabs, cleaning fluid, gloves, and basic service accessories.",
    price: "$72.00",
    badge: "Essential",
    badgeColor: "magenta" as const,
    image: "/images/pelmeltech/services-print-materials.webp",
  },
] as const;

export const PORTFOLIO_PROJECTS = [
  {
    title: "Global Tech Summit 2024",
    category: "Event Branding",
    description: "Comprehensive event branding and immersive environment design with precision color matching across 12,000 sqm of exhibition space.",
    featured: true,
    image: "/images/pelmeltech/portfolio-corporate-event.webp",
  },
  {
    title: "Flagship Retail Store",
    category: "Retail Display",
    description: "Full storefront vinyl and interior graphics for a luxury fashion brand's flagship location.",
    featured: false,
    image: "/images/pelmeltech/portfolio-retail-display.webp",
  },
  {
    title: "Corporate HQ Redesign",
    category: "Architectural Signage",
    description: "Complete wayfinding and brand integration for a Fortune 500 corporate campus.",
    featured: false,
    image: "/images/pelmeltech/portfolio-exhibition-panels.webp",
  },
  {
    title: "Music Festival Stage Design",
    category: "Event Printing",
    description: "Large-scale stage backdrops and environmental graphics for a 50,000-attendee music festival.",
    featured: false,
    image: "/images/pelmeltech/portfolio-stage-backdrop.webp",
  },
  {
    title: "Automotive Showroom",
    category: "Premium Display",
    description: "High-resolution wall murals and lightbox displays for a premium automotive dealership network.",
    featured: false,
    image: "/images/pelmeltech/portfolio-poster-campaign.webp",
  },
  {
    title: "Urban Billboard Campaign",
    category: "Outdoor Advertising",
    description: "City-wide billboard campaign with weather-resistant large format prints across 40 locations.",
    featured: false,
    image: "/images/pelmeltech/portfolio-outdoor-campaign.webp",
  },
] as const;

export const STATS = [
  { value: 250, suffix: "+", label: "Global Partners" },
  { value: 99.8, suffix: "%", label: "Color Accuracy" },
  { value: 0.01, suffix: "mm", label: "Print Tolerance" },
  { value: 24, suffix: "/7", label: "Production Capacity" },
] as const;

export const TESTIMONIALS = [
  {
    quote: "PelmelTech's attention to color accuracy and structural integrity is unparalleled. They handled our multi-city rollout without a single defect.",
    author: "Jane Doe",
    role: "CMO, Zenith Global",
    initials: "JD",
  },
  {
    quote: "The precision in their large-format prints transformed our exhibition presence. A truly professional partner from design to final install.",
    author: "Mark Sloan",
    role: "Director of Logistics, Aerotech",
    initials: "MS",
  },
  {
    quote: "Exceptional service. Their ability to handle high-volume, premium requests with tight deadlines has made them our go-to printing agency.",
    author: "Robert Lee",
    role: "Founder, Luminous Design",
    initials: "RL",
  },
] as const;
